Allow setting hostNetwork and securityContext in values.yaml
freifunkMUC/wg-access-server-chart pull request #16
Opened 2023-03-20 15:13 UTC by gdromanov

This PR allows setting `hostNetwork` and `securityContext` for the main container via `values.yaml` while keeping the current values as the default.

The use cases for setting non-default values for these variables are described in the comments in `values.yaml`.

While `hostNetwork` is almost self-explanatory, I feel like `securityContext` needs some extra explanation, so I'll provide it below.

For some reason, the container fails to start on my servers unless the `NET_RAW` capability is added. The error message looks like this:
`time="2023-03-20T12:50:26Z" level=error msg="failed to read table filter: running [/sbin/iptables -t filter -S WG_ACCESS_SERVER_FORWARD 1 --wait]: exit status 3: iptables v1.8.8 (legacy): can't initialize iptables table 'filter': Permission denied (you must be root)\nPerhaps iptables or your kernel needs to be upgraded.\n" file="main.go:152"`

Most probably, the reason for that is a specific kernel or iptables version, which I'm too lazy to investigate. Even if I'm somehow wrong, having a couple of extra settings for the chart won't do any harm (granted that the defaults remain unchanged, of course :)).
```
[root@k8s-dmz-01-ng-vpn-02-0 ~]# cat /etc/*release | head -n 1
AlmaLinux release 9.0 (Emerald Puma)
[root@k8s-dmz-01-ng-vpn-02-0 ~]# uname -r
5.14.0-70.17.1.el9_0.x86_64
[root@k8s-dmz-01-ng-vpn-02-0 ~]# yum list installed | grep iptables
iptables-libs.x86_64                 1.8.7-28.el9                  @baseos
iptables-nft.x86_64                  1.8.7-28.el9                  @baseos
```

2023-03-22 08:00 UTC, gdromanov commented
Whoops, almost forgot to update README. Also, on second thought, the description in the `values.yaml` should be adjusted a bit to keep the terminology precise.

2023-04-07 12:57 UTC, GoliathLabs requested changes
Hello @gdromanov,
thank you for your PR. Can you please bump the chart version? Otherwise your changes look good to me.

2023-04-07 14:18 UTC, gdromanov commented
@GoliathLabs, thanks! Done.

2023-04-07 14:23 UTC, GoliathLabs approved these changes

2023-04-07 14:23 UTC, merged

2023-04-07 14:23 UTC, GoliathLabs commented
Thank you! Merged 😄